{
  "formatVersion": "1.1",
  "component": {
    "group": "net.discdd",
    "module": "DDD-signal-protocol-java",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DDD-signal-protocol-java-2.8.1.jar",
          "url": "DDD-signal-protocol-java-2.8.1.jar",
          "size": 264483,
          "sha512": "ff7e0357645a097e178da825e233390c106a81815b20cb01e501208bbf376c73737162974258d2f7c6ad99ebb5102dc16da349a9b8c35ad85784e05a4f6f5770",
          "sha256": "9e0dacc0199b1e0a67ebe601e7ec8b051fd1d247c07a920d906616cc7d783022",
          "sha1": "0b4dfd619ff136ad4474a616e068d834c77a6ecf",
          "md5": "1bfe9cf9a8fb27377171cf0ef5f2f82e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.whispersystems",
          "module": "curve25519-java",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.23.4"
          }
        }
      ],
      "files": [
        {
          "name": "DDD-signal-protocol-java-2.8.1.jar",
          "url": "DDD-signal-protocol-java-2.8.1.jar",
          "size": 264483,
          "sha512": "ff7e0357645a097e178da825e233390c106a81815b20cb01e501208bbf376c73737162974258d2f7c6ad99ebb5102dc16da349a9b8c35ad85784e05a4f6f5770",
          "sha256": "9e0dacc0199b1e0a67ebe601e7ec8b051fd1d247c07a920d906616cc7d783022",
          "sha1": "0b4dfd619ff136ad4474a616e068d834c77a6ecf",
          "md5": "1bfe9cf9a8fb27377171cf0ef5f2f82e"
        }
      ]
    }
  ]
}
