// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebSocketResources.proto

package org.whispersystems.signalservice.internal.websocket;

public final class WebSocketProtos {
    private WebSocketProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }
    public interface WebSocketRequestMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:signalservice.WebSocketRequestMessage)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional string verb = 1;</code>
         * @return Whether the verb field is set.
         */
        boolean hasVerb();
        /**
         * <code>optional string verb = 1;</code>
         * @return The verb.
         */
        java.lang.String getVerb();
        /**
         * <code>optional string verb = 1;</code>
         * @return The bytes for verb.
         */
        com.google.protobuf.ByteString
        getVerbBytes();

        /**
         * <code>optional string path = 2;</code>
         * @return Whether the path field is set.
         */
        boolean hasPath();
        /**
         * <code>optional string path = 2;</code>
         * @return The path.
         */
        java.lang.String getPath();
        /**
         * <code>optional string path = 2;</code>
         * @return The bytes for path.
         */
        com.google.protobuf.ByteString
        getPathBytes();

        /**
         * <code>optional bytes body = 3;</code>
         * @return Whether the body field is set.
         */
        boolean hasBody();
        /**
         * <code>optional bytes body = 3;</code>
         * @return The body.
         */
        com.google.protobuf.ByteString getBody();

        /**
         * <code>repeated string headers = 5;</code>
         * @return A list containing the headers.
         */
        java.util.List<java.lang.String>
        getHeadersList();
        /**
         * <code>repeated string headers = 5;</code>
         * @return The count of headers.
         */
        int getHeadersCount();
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index of the element to return.
         * @return The headers at the given index.
         */
        java.lang.String getHeaders(int index);
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index of the element to return.
         * @return The headers at the given index.
         */
        com.google.protobuf.ByteString
        getHeadersBytes(int index);

        /**
         * <code>optional uint64 id = 4;</code>
         * @return Whether the id field is set.
         */
        boolean hasId();
        /**
         * <code>optional uint64 id = 4;</code>
         * @return The id.
         */
        long getId();
    }
    /**
     * Protobuf type {@code signalservice.WebSocketRequestMessage}
     */
    public  static final class WebSocketRequestMessage extends
            com.google.protobuf.GeneratedMessageLite<
                    WebSocketRequestMessage, WebSocketRequestMessage.Builder> implements
            // @@protoc_insertion_point(message_implements:signalservice.WebSocketRequestMessage)
            WebSocketRequestMessageOrBuilder {
        private WebSocketRequestMessage() {
            verb_ = "";
            path_ = "";
            body_ = com.google.protobuf.ByteString.EMPTY;
            headers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        }
        private int bitField0_;
        public static final int VERB_FIELD_NUMBER = 1;
        private java.lang.String verb_;
        /**
         * <code>optional string verb = 1;</code>
         * @return Whether the verb field is set.
         */
        @java.lang.Override
        public boolean hasVerb() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string verb = 1;</code>
         * @return The verb.
         */
        @java.lang.Override
        public java.lang.String getVerb() {
            return verb_;
        }
        /**
         * <code>optional string verb = 1;</code>
         * @return The bytes for verb.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getVerbBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(verb_);
        }
        /**
         * <code>optional string verb = 1;</code>
         * @param value The verb to set.
         */
        private void setVerb(
                java.lang.String value) {
            java.lang.Class<?> valueClass = value.getClass();
            bitField0_ |= 0x00000001;
            verb_ = value;
        }
        /**
         * <code>optional string verb = 1;</code>
         */
        private void clearVerb() {
            bitField0_ = (bitField0_ & ~0x00000001);
            verb_ = getDefaultInstance().getVerb();
        }
        /**
         * <code>optional string verb = 1;</code>
         * @param value The bytes for verb to set.
         */
        private void setVerbBytes(
                com.google.protobuf.ByteString value) {
            verb_ = value.toStringUtf8();
            bitField0_ |= 0x00000001;
        }

        public static final int PATH_FIELD_NUMBER = 2;
        private java.lang.String path_;
        /**
         * <code>optional string path = 2;</code>
         * @return Whether the path field is set.
         */
        @java.lang.Override
        public boolean hasPath() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional string path = 2;</code>
         * @return The path.
         */
        @java.lang.Override
        public java.lang.String getPath() {
            return path_;
        }
        /**
         * <code>optional string path = 2;</code>
         * @return The bytes for path.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getPathBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(path_);
        }
        /**
         * <code>optional string path = 2;</code>
         * @param value The path to set.
         */
        private void setPath(
                java.lang.String value) {
            java.lang.Class<?> valueClass = value.getClass();
            bitField0_ |= 0x00000002;
            path_ = value;
        }
        /**
         * <code>optional string path = 2;</code>
         */
        private void clearPath() {
            bitField0_ = (bitField0_ & ~0x00000002);
            path_ = getDefaultInstance().getPath();
        }
        /**
         * <code>optional string path = 2;</code>
         * @param value The bytes for path to set.
         */
        private void setPathBytes(
                com.google.protobuf.ByteString value) {
            path_ = value.toStringUtf8();
            bitField0_ |= 0x00000002;
        }

        public static final int BODY_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString body_;
        /**
         * <code>optional bytes body = 3;</code>
         * @return Whether the body field is set.
         */
        @java.lang.Override
        public boolean hasBody() {
            return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional bytes body = 3;</code>
         * @return The body.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }
        /**
         * <code>optional bytes body = 3;</code>
         * @param value The body to set.
         */
        private void setBody(com.google.protobuf.ByteString value) {
            java.lang.Class<?> valueClass = value.getClass();
            bitField0_ |= 0x00000004;
            body_ = value;
        }
        /**
         * <code>optional bytes body = 3;</code>
         */
        private void clearBody() {
            bitField0_ = (bitField0_ & ~0x00000004);
            body_ = getDefaultInstance().getBody();
        }

        public static final int HEADERS_FIELD_NUMBER = 5;
        private com.google.protobuf.Internal.ProtobufList<java.lang.String> headers_;
        /**
         * <code>repeated string headers = 5;</code>
         * @return A list containing the headers.
         */
        @java.lang.Override
        public java.util.List<java.lang.String> getHeadersList() {
            return headers_;
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @return The count of headers.
         */
        @java.lang.Override
        public int getHeadersCount() {
            return headers_.size();
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index of the element to return.
         * @return The headers at the given index.
         */
        @java.lang.Override
        public java.lang.String getHeaders(int index) {
            return headers_.get(index);
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index of the value to return.
         * @return The bytes of the headers at the given index.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getHeadersBytes(int index) {
            return com.google.protobuf.ByteString.copyFromUtf8(
                    headers_.get(index));
        }
        private void ensureHeadersIsMutable() {
            com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
                    headers_;  if (!tmp.isModifiable()) {
                headers_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
            }
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index to set the value at.
         * @param value The headers to set.
         */
        private void setHeaders(
                int index, java.lang.String value) {
            java.lang.Class<?> valueClass = value.getClass();
            ensureHeadersIsMutable();
            headers_.set(index, value);
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param value The headers to add.
         */
        private void addHeaders(
                java.lang.String value) {
            java.lang.Class<?> valueClass = value.getClass();
            ensureHeadersIsMutable();
            headers_.add(value);
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param values The headers to add.
         */
        private void addAllHeaders(
                java.lang.Iterable<java.lang.String> values) {
            ensureHeadersIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, headers_);
        }
        /**
         * <code>repeated string headers = 5;</code>
         */
        private void clearHeaders() {
            headers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param value The bytes of the headers to add.
         */
        private void addHeadersBytes(
                com.google.protobuf.ByteString value) {
            ensureHeadersIsMutable();
            headers_.add(value.toStringUtf8());
        }

        public static final int ID_FIELD_NUMBER = 4;
        private long id_;
        /**
         * <code>optional uint64 id = 4;</code>
         * @return Whether the id field is set.
         */
        @java.lang.Override
        public boolean hasId() {
            return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional uint64 id = 4;</code>
         * @return The id.
         */
        @java.lang.Override
        public long getId() {
            return id_;
        }
        /**
         * <code>optional uint64 id = 4;</code>
         * @param value The id to set.
         */
        private void setId(long value) {
            bitField0_ |= 0x00000008;
            id_ = value;
        }
        /**
         * <code>optional uint64 id = 4;</code>
         */
        private void clearId() {
            bitField0_ = (bitField0_ & ~0x00000008);
            id_ = 0L;
        }

        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }
        public static Builder newBuilder(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * Protobuf type {@code signalservice.WebSocketRequestMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage, Builder> implements
                // @@protoc_insertion_point(builder_implements:signalservice.WebSocketRequestMessage)
                org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessageOrBuilder {
            // Construct using org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional string verb = 1;</code>
             * @return Whether the verb field is set.
             */
            @java.lang.Override
            public boolean hasVerb() {
                return instance.hasVerb();
            }
            /**
             * <code>optional string verb = 1;</code>
             * @return The verb.
             */
            @java.lang.Override
            public java.lang.String getVerb() {
                return instance.getVerb();
            }
            /**
             * <code>optional string verb = 1;</code>
             * @return The bytes for verb.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getVerbBytes() {
                return instance.getVerbBytes();
            }
            /**
             * <code>optional string verb = 1;</code>
             * @param value The verb to set.
             * @return This builder for chaining.
             */
            public Builder setVerb(
                    java.lang.String value) {
                copyOnWrite();
                instance.setVerb(value);
                return this;
            }
            /**
             * <code>optional string verb = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearVerb() {
                copyOnWrite();
                instance.clearVerb();
                return this;
            }
            /**
             * <code>optional string verb = 1;</code>
             * @param value The bytes for verb to set.
             * @return This builder for chaining.
             */
            public Builder setVerbBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setVerbBytes(value);
                return this;
            }

            /**
             * <code>optional string path = 2;</code>
             * @return Whether the path field is set.
             */
            @java.lang.Override
            public boolean hasPath() {
                return instance.hasPath();
            }
            /**
             * <code>optional string path = 2;</code>
             * @return The path.
             */
            @java.lang.Override
            public java.lang.String getPath() {
                return instance.getPath();
            }
            /**
             * <code>optional string path = 2;</code>
             * @return The bytes for path.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getPathBytes() {
                return instance.getPathBytes();
            }
            /**
             * <code>optional string path = 2;</code>
             * @param value The path to set.
             * @return This builder for chaining.
             */
            public Builder setPath(
                    java.lang.String value) {
                copyOnWrite();
                instance.setPath(value);
                return this;
            }
            /**
             * <code>optional string path = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearPath() {
                copyOnWrite();
                instance.clearPath();
                return this;
            }
            /**
             * <code>optional string path = 2;</code>
             * @param value The bytes for path to set.
             * @return This builder for chaining.
             */
            public Builder setPathBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setPathBytes(value);
                return this;
            }

            /**
             * <code>optional bytes body = 3;</code>
             * @return Whether the body field is set.
             */
            @java.lang.Override
            public boolean hasBody() {
                return instance.hasBody();
            }
            /**
             * <code>optional bytes body = 3;</code>
             * @return The body.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getBody() {
                return instance.getBody();
            }
            /**
             * <code>optional bytes body = 3;</code>
             * @param value The body to set.
             * @return This builder for chaining.
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setBody(value);
                return this;
            }
            /**
             * <code>optional bytes body = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearBody() {
                copyOnWrite();
                instance.clearBody();
                return this;
            }

            /**
             * <code>repeated string headers = 5;</code>
             * @return A list containing the headers.
             */
            @java.lang.Override
            public java.util.List<java.lang.String>
            getHeadersList() {
                return java.util.Collections.unmodifiableList(
                        instance.getHeadersList());
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @return The count of headers.
             */
            @java.lang.Override
            public int getHeadersCount() {
                return instance.getHeadersCount();
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param index The index of the element to return.
             * @return The headers at the given index.
             */
            @java.lang.Override
            public java.lang.String getHeaders(int index) {
                return instance.getHeaders(index);
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param index The index of the value to return.
             * @return The bytes of the headers at the given index.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getHeadersBytes(int index) {
                return instance.getHeadersBytes(index);
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param index The index to set the value at.
             * @param value The headers to set.
             * @return This builder for chaining.
             */
            public Builder setHeaders(
                    int index, java.lang.String value) {
                copyOnWrite();
                instance.setHeaders(index, value);
                return this;
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param value The headers to add.
             * @return This builder for chaining.
             */
            public Builder addHeaders(
                    java.lang.String value) {
                copyOnWrite();
                instance.addHeaders(value);
                return this;
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param values The headers to add.
             * @return This builder for chaining.
             */
            public Builder addAllHeaders(
                    java.lang.Iterable<java.lang.String> values) {
                copyOnWrite();
                instance.addAllHeaders(values);
                return this;
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearHeaders() {
                copyOnWrite();
                instance.clearHeaders();
                return this;
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param value The bytes of the headers to add.
             * @return This builder for chaining.
             */
            public Builder addHeadersBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.addHeadersBytes(value);
                return this;
            }

            /**
             * <code>optional uint64 id = 4;</code>
             * @return Whether the id field is set.
             */
            @java.lang.Override
            public boolean hasId() {
                return instance.hasId();
            }
            /**
             * <code>optional uint64 id = 4;</code>
             * @return The id.
             */
            @java.lang.Override
            public long getId() {
                return instance.getId();
            }
            /**
             * <code>optional uint64 id = 4;</code>
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(long value) {
                copyOnWrite();
                instance.setId(value);
                return this;
            }
            /**
             * <code>optional uint64 id = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearId() {
                copyOnWrite();
                instance.clearId();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:signalservice.WebSocketRequestMessage)
        }
        @java.lang.Override
        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    java.lang.Object[] objects = new java.lang.Object[] {
                            "bitField0_",
                            "verb_",
                            "path_",
                            "body_",
                            "id_",
                            "headers_",
                    };
                    java.lang.String info =
                            "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u1008\u0000\u0002" +
                                    "\u1008\u0001\u0003\u100a\u0002\u0004\u1003\u0003\u0005\u001a";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage> parser = PARSER;
                    if (parser == null) {
                        synchronized (org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:signalservice.WebSocketRequestMessage)
        private static final org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage DEFAULT_INSTANCE;
        static {
            WebSocketRequestMessage defaultInstance = new WebSocketRequestMessage();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    WebSocketRequestMessage.class, defaultInstance);
        }

        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<WebSocketRequestMessage> PARSER;

        public static com.google.protobuf.Parser<WebSocketRequestMessage> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface WebSocketResponseMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:signalservice.WebSocketResponseMessage)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional uint64 id = 1;</code>
         * @return Whether the id field is set.
         */
        boolean hasId();
        /**
         * <code>optional uint64 id = 1;</code>
         * @return The id.
         */
        long getId();

        /**
         * <code>optional uint32 status = 2;</code>
         * @return Whether the status field is set.
         */
        boolean hasStatus();
        /**
         * <code>optional uint32 status = 2;</code>
         * @return The status.
         */
        int getStatus();

        /**
         * <code>optional string message = 3;</code>
         * @return Whether the message field is set.
         */
        boolean hasMessage();
        /**
         * <code>optional string message = 3;</code>
         * @return The message.
         */
        java.lang.String getMessage();
        /**
         * <code>optional string message = 3;</code>
         * @return The bytes for message.
         */
        com.google.protobuf.ByteString
        getMessageBytes();

        /**
         * <code>repeated string headers = 5;</code>
         * @return A list containing the headers.
         */
        java.util.List<java.lang.String>
        getHeadersList();
        /**
         * <code>repeated string headers = 5;</code>
         * @return The count of headers.
         */
        int getHeadersCount();
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index of the element to return.
         * @return The headers at the given index.
         */
        java.lang.String getHeaders(int index);
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index of the element to return.
         * @return The headers at the given index.
         */
        com.google.protobuf.ByteString
        getHeadersBytes(int index);

        /**
         * <code>optional bytes body = 4;</code>
         * @return Whether the body field is set.
         */
        boolean hasBody();
        /**
         * <code>optional bytes body = 4;</code>
         * @return The body.
         */
        com.google.protobuf.ByteString getBody();
    }
    /**
     * Protobuf type {@code signalservice.WebSocketResponseMessage}
     */
    public  static final class WebSocketResponseMessage extends
            com.google.protobuf.GeneratedMessageLite<
                    WebSocketResponseMessage, WebSocketResponseMessage.Builder> implements
            // @@protoc_insertion_point(message_implements:signalservice.WebSocketResponseMessage)
            WebSocketResponseMessageOrBuilder {
        private WebSocketResponseMessage() {
            message_ = "";
            headers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
            body_ = com.google.protobuf.ByteString.EMPTY;
        }
        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private long id_;
        /**
         * <code>optional uint64 id = 1;</code>
         * @return Whether the id field is set.
         */
        @java.lang.Override
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional uint64 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public long getId() {
            return id_;
        }
        /**
         * <code>optional uint64 id = 1;</code>
         * @param value The id to set.
         */
        private void setId(long value) {
            bitField0_ |= 0x00000001;
            id_ = value;
        }
        /**
         * <code>optional uint64 id = 1;</code>
         */
        private void clearId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            id_ = 0L;
        }

        public static final int STATUS_FIELD_NUMBER = 2;
        private int status_;
        /**
         * <code>optional uint32 status = 2;</code>
         * @return Whether the status field is set.
         */
        @java.lang.Override
        public boolean hasStatus() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional uint32 status = 2;</code>
         * @return The status.
         */
        @java.lang.Override
        public int getStatus() {
            return status_;
        }
        /**
         * <code>optional uint32 status = 2;</code>
         * @param value The status to set.
         */
        private void setStatus(int value) {
            bitField0_ |= 0x00000002;
            status_ = value;
        }
        /**
         * <code>optional uint32 status = 2;</code>
         */
        private void clearStatus() {
            bitField0_ = (bitField0_ & ~0x00000002);
            status_ = 0;
        }

        public static final int MESSAGE_FIELD_NUMBER = 3;
        private java.lang.String message_;
        /**
         * <code>optional string message = 3;</code>
         * @return Whether the message field is set.
         */
        @java.lang.Override
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional string message = 3;</code>
         * @return The message.
         */
        @java.lang.Override
        public java.lang.String getMessage() {
            return message_;
        }
        /**
         * <code>optional string message = 3;</code>
         * @return The bytes for message.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getMessageBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(message_);
        }
        /**
         * <code>optional string message = 3;</code>
         * @param value The message to set.
         */
        private void setMessage(
                java.lang.String value) {
            java.lang.Class<?> valueClass = value.getClass();
            bitField0_ |= 0x00000004;
            message_ = value;
        }
        /**
         * <code>optional string message = 3;</code>
         */
        private void clearMessage() {
            bitField0_ = (bitField0_ & ~0x00000004);
            message_ = getDefaultInstance().getMessage();
        }
        /**
         * <code>optional string message = 3;</code>
         * @param value The bytes for message to set.
         */
        private void setMessageBytes(
                com.google.protobuf.ByteString value) {
            message_ = value.toStringUtf8();
            bitField0_ |= 0x00000004;
        }

        public static final int HEADERS_FIELD_NUMBER = 5;
        private com.google.protobuf.Internal.ProtobufList<java.lang.String> headers_;
        /**
         * <code>repeated string headers = 5;</code>
         * @return A list containing the headers.
         */
        @java.lang.Override
        public java.util.List<java.lang.String> getHeadersList() {
            return headers_;
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @return The count of headers.
         */
        @java.lang.Override
        public int getHeadersCount() {
            return headers_.size();
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index of the element to return.
         * @return The headers at the given index.
         */
        @java.lang.Override
        public java.lang.String getHeaders(int index) {
            return headers_.get(index);
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index of the value to return.
         * @return The bytes of the headers at the given index.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getHeadersBytes(int index) {
            return com.google.protobuf.ByteString.copyFromUtf8(
                    headers_.get(index));
        }
        private void ensureHeadersIsMutable() {
            com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
                    headers_;  if (!tmp.isModifiable()) {
                headers_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
            }
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param index The index to set the value at.
         * @param value The headers to set.
         */
        private void setHeaders(
                int index, java.lang.String value) {
            java.lang.Class<?> valueClass = value.getClass();
            ensureHeadersIsMutable();
            headers_.set(index, value);
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param value The headers to add.
         */
        private void addHeaders(
                java.lang.String value) {
            java.lang.Class<?> valueClass = value.getClass();
            ensureHeadersIsMutable();
            headers_.add(value);
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param values The headers to add.
         */
        private void addAllHeaders(
                java.lang.Iterable<java.lang.String> values) {
            ensureHeadersIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, headers_);
        }
        /**
         * <code>repeated string headers = 5;</code>
         */
        private void clearHeaders() {
            headers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        }
        /**
         * <code>repeated string headers = 5;</code>
         * @param value The bytes of the headers to add.
         */
        private void addHeadersBytes(
                com.google.protobuf.ByteString value) {
            ensureHeadersIsMutable();
            headers_.add(value.toStringUtf8());
        }

        public static final int BODY_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString body_;
        /**
         * <code>optional bytes body = 4;</code>
         * @return Whether the body field is set.
         */
        @java.lang.Override
        public boolean hasBody() {
            return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional bytes body = 4;</code>
         * @return The body.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }
        /**
         * <code>optional bytes body = 4;</code>
         * @param value The body to set.
         */
        private void setBody(com.google.protobuf.ByteString value) {
            java.lang.Class<?> valueClass = value.getClass();
            bitField0_ |= 0x00000008;
            body_ = value;
        }
        /**
         * <code>optional bytes body = 4;</code>
         */
        private void clearBody() {
            bitField0_ = (bitField0_ & ~0x00000008);
            body_ = getDefaultInstance().getBody();
        }

        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }
        public static Builder newBuilder(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * Protobuf type {@code signalservice.WebSocketResponseMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage, Builder> implements
                // @@protoc_insertion_point(builder_implements:signalservice.WebSocketResponseMessage)
                org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessageOrBuilder {
            // Construct using org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional uint64 id = 1;</code>
             * @return Whether the id field is set.
             */
            @java.lang.Override
            public boolean hasId() {
                return instance.hasId();
            }
            /**
             * <code>optional uint64 id = 1;</code>
             * @return The id.
             */
            @java.lang.Override
            public long getId() {
                return instance.getId();
            }
            /**
             * <code>optional uint64 id = 1;</code>
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(long value) {
                copyOnWrite();
                instance.setId(value);
                return this;
            }
            /**
             * <code>optional uint64 id = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearId() {
                copyOnWrite();
                instance.clearId();
                return this;
            }

            /**
             * <code>optional uint32 status = 2;</code>
             * @return Whether the status field is set.
             */
            @java.lang.Override
            public boolean hasStatus() {
                return instance.hasStatus();
            }
            /**
             * <code>optional uint32 status = 2;</code>
             * @return The status.
             */
            @java.lang.Override
            public int getStatus() {
                return instance.getStatus();
            }
            /**
             * <code>optional uint32 status = 2;</code>
             * @param value The status to set.
             * @return This builder for chaining.
             */
            public Builder setStatus(int value) {
                copyOnWrite();
                instance.setStatus(value);
                return this;
            }
            /**
             * <code>optional uint32 status = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearStatus() {
                copyOnWrite();
                instance.clearStatus();
                return this;
            }

            /**
             * <code>optional string message = 3;</code>
             * @return Whether the message field is set.
             */
            @java.lang.Override
            public boolean hasMessage() {
                return instance.hasMessage();
            }
            /**
             * <code>optional string message = 3;</code>
             * @return The message.
             */
            @java.lang.Override
            public java.lang.String getMessage() {
                return instance.getMessage();
            }
            /**
             * <code>optional string message = 3;</code>
             * @return The bytes for message.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getMessageBytes() {
                return instance.getMessageBytes();
            }
            /**
             * <code>optional string message = 3;</code>
             * @param value The message to set.
             * @return This builder for chaining.
             */
            public Builder setMessage(
                    java.lang.String value) {
                copyOnWrite();
                instance.setMessage(value);
                return this;
            }
            /**
             * <code>optional string message = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearMessage() {
                copyOnWrite();
                instance.clearMessage();
                return this;
            }
            /**
             * <code>optional string message = 3;</code>
             * @param value The bytes for message to set.
             * @return This builder for chaining.
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setMessageBytes(value);
                return this;
            }

            /**
             * <code>repeated string headers = 5;</code>
             * @return A list containing the headers.
             */
            @java.lang.Override
            public java.util.List<java.lang.String>
            getHeadersList() {
                return java.util.Collections.unmodifiableList(
                        instance.getHeadersList());
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @return The count of headers.
             */
            @java.lang.Override
            public int getHeadersCount() {
                return instance.getHeadersCount();
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param index The index of the element to return.
             * @return The headers at the given index.
             */
            @java.lang.Override
            public java.lang.String getHeaders(int index) {
                return instance.getHeaders(index);
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param index The index of the value to return.
             * @return The bytes of the headers at the given index.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getHeadersBytes(int index) {
                return instance.getHeadersBytes(index);
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param index The index to set the value at.
             * @param value The headers to set.
             * @return This builder for chaining.
             */
            public Builder setHeaders(
                    int index, java.lang.String value) {
                copyOnWrite();
                instance.setHeaders(index, value);
                return this;
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param value The headers to add.
             * @return This builder for chaining.
             */
            public Builder addHeaders(
                    java.lang.String value) {
                copyOnWrite();
                instance.addHeaders(value);
                return this;
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param values The headers to add.
             * @return This builder for chaining.
             */
            public Builder addAllHeaders(
                    java.lang.Iterable<java.lang.String> values) {
                copyOnWrite();
                instance.addAllHeaders(values);
                return this;
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearHeaders() {
                copyOnWrite();
                instance.clearHeaders();
                return this;
            }
            /**
             * <code>repeated string headers = 5;</code>
             * @param value The bytes of the headers to add.
             * @return This builder for chaining.
             */
            public Builder addHeadersBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.addHeadersBytes(value);
                return this;
            }

            /**
             * <code>optional bytes body = 4;</code>
             * @return Whether the body field is set.
             */
            @java.lang.Override
            public boolean hasBody() {
                return instance.hasBody();
            }
            /**
             * <code>optional bytes body = 4;</code>
             * @return The body.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getBody() {
                return instance.getBody();
            }
            /**
             * <code>optional bytes body = 4;</code>
             * @param value The body to set.
             * @return This builder for chaining.
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setBody(value);
                return this;
            }
            /**
             * <code>optional bytes body = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearBody() {
                copyOnWrite();
                instance.clearBody();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:signalservice.WebSocketResponseMessage)
        }
        @java.lang.Override
        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    java.lang.Object[] objects = new java.lang.Object[] {
                            "bitField0_",
                            "id_",
                            "status_",
                            "message_",
                            "body_",
                            "headers_",
                    };
                    java.lang.String info =
                            "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u1003\u0000\u0002" +
                                    "\u100b\u0001\u0003\u1008\u0002\u0004\u100a\u0003\u0005\u001a";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage> parser = PARSER;
                    if (parser == null) {
                        synchronized (org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:signalservice.WebSocketResponseMessage)
        private static final org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage DEFAULT_INSTANCE;
        static {
            WebSocketResponseMessage defaultInstance = new WebSocketResponseMessage();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    WebSocketResponseMessage.class, defaultInstance);
        }

        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<WebSocketResponseMessage> PARSER;

        public static com.google.protobuf.Parser<WebSocketResponseMessage> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface WebSocketMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:signalservice.WebSocketMessage)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
         * @return Whether the type field is set.
         */
        boolean hasType();
        /**
         * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
         * @return The type.
         */
        org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type getType();

        /**
         * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
         * @return Whether the request field is set.
         */
        boolean hasRequest();
        /**
         * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
         * @return The request.
         */
        org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage getRequest();

        /**
         * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
         * @return Whether the response field is set.
         */
        boolean hasResponse();
        /**
         * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
         * @return The response.
         */
        org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage getResponse();
    }
    /**
     * Protobuf type {@code signalservice.WebSocketMessage}
     */
    public  static final class WebSocketMessage extends
            com.google.protobuf.GeneratedMessageLite<
                    WebSocketMessage, WebSocketMessage.Builder> implements
            // @@protoc_insertion_point(message_implements:signalservice.WebSocketMessage)
            WebSocketMessageOrBuilder {
        private WebSocketMessage() {
        }
        /**
         * Protobuf enum {@code signalservice.WebSocketMessage.Type}
         */
        public enum Type
                implements com.google.protobuf.Internal.EnumLite {
            /**
             * <code>UNKNOWN = 0;</code>
             */
            UNKNOWN(0),
            /**
             * <code>REQUEST = 1;</code>
             */
            REQUEST(1),
            /**
             * <code>RESPONSE = 2;</code>
             */
            RESPONSE(2),
            ;

            /**
             * <code>UNKNOWN = 0;</code>
             */
            public static final int UNKNOWN_VALUE = 0;
            /**
             * <code>REQUEST = 1;</code>
             */
            public static final int REQUEST_VALUE = 1;
            /**
             * <code>RESPONSE = 2;</code>
             */
            public static final int RESPONSE_VALUE = 2;


            @java.lang.Override
            public final int getNumber() {
                return value;
            }

            /**
             * @param value The number of the enum to look for.
             * @return The enum associated with the given number.
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Type valueOf(int value) {
                return forNumber(value);
            }

            public static Type forNumber(int value) {
                switch (value) {
                    case 0: return UNKNOWN;
                    case 1: return REQUEST;
                    case 2: return RESPONSE;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Type> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                        @java.lang.Override
                        public Type findValueByNumber(int number) {
                            return Type.forNumber(number);
                        }
                    };

            public static com.google.protobuf.Internal.EnumVerifier
            internalGetVerifier() {
                return TypeVerifier.INSTANCE;
            }

            private static final class TypeVerifier implements
                    com.google.protobuf.Internal.EnumVerifier {
                static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new TypeVerifier();
                @java.lang.Override
                public boolean isInRange(int number) {
                    return Type.forNumber(number) != null;
                }
            };

            private final int value;

            private Type(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:signalservice.WebSocketMessage.Type)
        }

        private int bitField0_;
        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;
        /**
         * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
         * @return Whether the type field is set.
         */
        @java.lang.Override
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
         * @return The type.
         */
        @java.lang.Override
        public org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type getType() {
            org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type result = org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type.forNumber(type_);
            return result == null ? org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type.UNKNOWN : result;
        }
        /**
         * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
         * @param value The type to set.
         */
        private void setType(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type value) {
            type_ = value.getNumber();
            bitField0_ |= 0x00000001;
        }
        /**
         * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
         */
        private void clearType() {
            bitField0_ = (bitField0_ & ~0x00000001);
            type_ = 0;
        }

        public static final int REQUEST_FIELD_NUMBER = 2;
        private org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage request_;
        /**
         * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
         */
        @java.lang.Override
        public boolean hasRequest() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
         */
        @java.lang.Override
        public org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage getRequest() {
            return request_ == null ? org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage.getDefaultInstance() : request_;
        }
        /**
         * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
         */
        private void setRequest(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage value) {
            value.getClass();
            request_ = value;
            bitField0_ |= 0x00000002;
        }
        /**
         * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
         */
        @java.lang.SuppressWarnings({"ReferenceEquality"})
        private void mergeRequest(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage value) {
            value.getClass();
            if (request_ != null &&
                    request_ != org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage.getDefaultInstance()) {
                request_ =
                        org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage.newBuilder(request_).mergeFrom(value).buildPartial();
            } else {
                request_ = value;
            }
            bitField0_ |= 0x00000002;
        }
        /**
         * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
         */
        private void clearRequest() {  request_ = null;
            bitField0_ = (bitField0_ & ~0x00000002);
        }

        public static final int RESPONSE_FIELD_NUMBER = 3;
        private org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage response_;
        /**
         * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
         */
        @java.lang.Override
        public boolean hasResponse() {
            return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
         */
        @java.lang.Override
        public org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage getResponse() {
            return response_ == null ? org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage.getDefaultInstance() : response_;
        }
        /**
         * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
         */
        private void setResponse(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage value) {
            value.getClass();
            response_ = value;
            bitField0_ |= 0x00000004;
        }
        /**
         * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
         */
        @java.lang.SuppressWarnings({"ReferenceEquality"})
        private void mergeResponse(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage value) {
            value.getClass();
            if (response_ != null &&
                    response_ != org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage.getDefaultInstance()) {
                response_ =
                        org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage.newBuilder(response_).mergeFrom(value).buildPartial();
            } else {
                response_ = value;
            }
            bitField0_ |= 0x00000004;
        }
        /**
         * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
         */
        private void clearResponse() {  response_ = null;
            bitField0_ = (bitField0_ & ~0x00000004);
        }

        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }
        public static Builder newBuilder(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * Protobuf type {@code signalservice.WebSocketMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage, Builder> implements
                // @@protoc_insertion_point(builder_implements:signalservice.WebSocketMessage)
                org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessageOrBuilder {
            // Construct using org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
             * @return Whether the type field is set.
             */
            @java.lang.Override
            public boolean hasType() {
                return instance.hasType();
            }
            /**
             * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
             * @return The type.
             */
            @java.lang.Override
            public org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type getType() {
                return instance.getType();
            }
            /**
             * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
             * @param value The enum numeric value on the wire for type to set.
             * @return This builder for chaining.
             */
            public Builder setType(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type value) {
                copyOnWrite();
                instance.setType(value);
                return this;
            }
            /**
             * <code>optional .signalservice.WebSocketMessage.Type type = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearType() {
                copyOnWrite();
                instance.clearType();
                return this;
            }

            /**
             * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
             */
            @java.lang.Override
            public boolean hasRequest() {
                return instance.hasRequest();
            }
            /**
             * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
             */
            @java.lang.Override
            public org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage getRequest() {
                return instance.getRequest();
            }
            /**
             * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
             */
            public Builder setRequest(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage value) {
                copyOnWrite();
                instance.setRequest(value);
                return this;
            }
            /**
             * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
             */
            public Builder setRequest(
                    org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage.Builder builderForValue) {
                copyOnWrite();
                instance.setRequest(builderForValue.build());
                return this;
            }
            /**
             * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
             */
            public Builder mergeRequest(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketRequestMessage value) {
                copyOnWrite();
                instance.mergeRequest(value);
                return this;
            }
            /**
             * <code>optional .signalservice.WebSocketRequestMessage request = 2;</code>
             */
            public Builder clearRequest() {  copyOnWrite();
                instance.clearRequest();
                return this;
            }

            /**
             * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
             */
            @java.lang.Override
            public boolean hasResponse() {
                return instance.hasResponse();
            }
            /**
             * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
             */
            @java.lang.Override
            public org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage getResponse() {
                return instance.getResponse();
            }
            /**
             * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
             */
            public Builder setResponse(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage value) {
                copyOnWrite();
                instance.setResponse(value);
                return this;
            }
            /**
             * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
             */
            public Builder setResponse(
                    org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage.Builder builderForValue) {
                copyOnWrite();
                instance.setResponse(builderForValue.build());
                return this;
            }
            /**
             * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
             */
            public Builder mergeResponse(org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketResponseMessage value) {
                copyOnWrite();
                instance.mergeResponse(value);
                return this;
            }
            /**
             * <code>optional .signalservice.WebSocketResponseMessage response = 3;</code>
             */
            public Builder clearResponse() {  copyOnWrite();
                instance.clearResponse();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:signalservice.WebSocketMessage)
        }
        @java.lang.Override
        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    java.lang.Object[] objects = new java.lang.Object[] {
                            "bitField0_",
                            "type_",
                            org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.Type.internalGetVerifier(),
                            "request_",
                            "response_",
                    };
                    java.lang.String info =
                            "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u100c\u0000\u0002" +
                                    "\u1009\u0001\u0003\u1009\u0002";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage> parser = PARSER;
                    if (parser == null) {
                        synchronized (org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:signalservice.WebSocketMessage)
        private static final org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage DEFAULT_INSTANCE;
        static {
            WebSocketMessage defaultInstance = new WebSocketMessage();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    WebSocketMessage.class, defaultInstance);
        }

        public static org.whispersystems.signalservice.internal.websocket.WebSocketProtos.WebSocketMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<WebSocketMessage> PARSER;

        public static com.google.protobuf.Parser<WebSocketMessage> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
