# Add to the top of your workflow YAML for VSCode / YAML validation
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Runner Health Check and Full Test


on:
  schedule:
    - cron: '0 11 * * *'
  pull_request:
    branches: [main]
    paths: [.github/workflows/daily.yml]
  workflow_dispatch:

permissions:
  actions: read  # allow reading workflow job status
  contents: read # allow read access to repo contents (often needed)

# we are doing a subtle trick to avoid hanging forever if a machine is down:
#     the job running on ubuntu-latest will fail after 15 minutes. that will
#     cause the whole daily job to fail and cancel the hung jobs going to
#     runners that are down. that is why we skip most of the steps where
#     ubuntu-latest is in the runner list and on the last step we sleep for
#     15 minutes and then fail.
#
# this trick means that the jobs will always take at least 15 minutes, since
# that is how long the timeout job is going to take, and all runs of daily
# will end in failure. for the report job, we will get the status of each
# of the runners (skipping the ubuntu-latest runner that times out) and
# figure out the actual success of the run.

jobs:
  daily:
    timeout-minutes: 20
    strategy:
      max-parallel: 3  # don't use up all the runners
      matrix:
        # tragically, there isn't a nice way to dynamically build this list...
        runner:
          - [self-hosted, cs-reed-02]
          - [self-hosted, cs-reed-03]
          - [self-hosted, cs-reed-04]
          - [self-hosted, SJSU-office]
          - [ubuntu-latest]
    outputs:
      # i was hoping that we could make use of these outputs, but they don't
      # get aggregated properly to be useful :'( it was hard to figure out
      # how it all works. i'm leaving here just in case aggregation starts
      # working in the future
      timeout: ${{ steps.timeout.outputs.timeout }}
      started: ${{ steps.started.outputs.started }}
      finished: ${{ steps.finished.outputs.finished }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Print runner info
        run: 'echo "Running test "'

      - name: Ensure Android Emulator is Running
        if: contains(matrix.runner, 'ubuntu-latest') == false
        id: started
        run: |
            echo "started='${{ matrix.runner[1] }}'" >> $GITHUB_OUTPUT
            if adb devices | grep "emulator"
            then
                echo "Emulator already running."
            else
                echo "Starting emulator..."
                set +e
                sudo chmod o+r,o+w /dev/kvm
                set -e
                nohup emulator -avd test_avd-33 -no-window -no-audio -gpu swiftshader_indirect -no-snapshot -wipe-data > /tmp/emulator.log 2>&1 &
            fi

      - name: Checkout
        if: contains(matrix.runner, 'ubuntu-latest') == false
        uses: actions/checkout@v4

      - name: Maven install
        if: contains(matrix.runner, 'ubuntu-latest') == false
        run: |
            mvn -ntp install

      - name: Gradle connected tests
        if: contains(matrix.runner, 'ubuntu-latest') == false
        id: finished
        run: |
            if adb devices | grep "emulator"
            then
                echo "Emulator already running."
                set +e
                # we don't want to immediately fail on an error since we want to
                # collect the logs and print those before we exit with the actual
                # exit code
                ./gradlew connectedDebugAndroidTest --parallel
                TEST_RESULT=$?
                set -e
                adb logcat -s TestRunner -d
                echo "finished=$TEST_RESULT" >> $GITHUB_OUTPUT
                exit $TEST_RESULT
            else
                echo "Emulator not running"
                exit 1
            fi

      - name: Fail after 15 minutes
        # this runner just waits for 15 minutes to fail. it is the only thing
        # that ubuntu-latest does for this job. as a side effect it will kill
        # any stuck runners
        if: contains(matrix.runner, 'ubuntu-latest')
        id: timeout
        run: |
             sleep 900
             echo "timeout=TIMEOUT" >> $GITHUB_OUTPUT
             exit 1

  report:
    needs: daily
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        # collect the result of the runs using the web API
        run: |
            curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
             "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs?per_page=100" > results
            cancelled=$(jq '[.jobs[] | select((.name | contains("self-hosted")) and (.conclusion == "cancelled"))] | length' results)
            success=$(jq '[.jobs[] | select((.name | contains("self-hosted")) and (.conclusion == "success"))] | length' results)
            failed=$(jq '[.jobs[] | select((.name | contains("self-hosted")) and (.conclusion == "failure"))] | length' results)
            if [[ "$success" > 0 && "$cancelled" == 0 && "$failed" == 0 ]]
            then
                echo 'SUCCESS'
                exit 0
            else
                echo "$cancelled Cancelled, $failed Failed, $success Success"
                exit 1
            fi
